import Head from 'next/head';
import SideBar from 'components/SideBar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>GoLive Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SideBar />
      </main>

      <footer></footer>
    </div>
  );
}
